version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
    
volumes:
  mongodb_data_container:
